//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WepSiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LienHe
    {
        public int Id { get; set; }
        public string ThongTin { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string HoTen { get; set; }
        public string DienThoai { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public string YeuCau { get; set; }
    }
}
